title: UoL NLP Group
description: University of Liverpool, Natural Language Processing Group


baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
#url: "https://livnlp.github.io" # change this to the base hostname & protocol for your site


theme: jekyll-theme-slate

# social
author: 
  name: University of Liverpool, NLP Group

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

header_page_refs: ['publications', 'reading']
