theme: jekyll-theme-cayman

title:        University of Liverpool, Natural Language Processing Group
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Danushka Bollegala
  url:        https://danushka.net